# cross entropy weight
alpha: 1.
# recurrent architecture
arch: gru
# gmm energy weight 0.001
beta: 0.00001
# singularity weight 0.005
gamma: 0.000001
# batch size
bs: 512
# dropout
do: 0.25
# learning rate
lr: 0.0005
# estimation network size
ne: 16
# recurrent network size
nh: 96
# latent space size
nl: 8
# number of recurrent layers
nlayers: 2
# output size
nout: 1
# weight decay weight
wd: 0.0
# lc folding
fold: false
