# cross entropy weight
alpha: 1.
# recurrent architecture
arch: gru
# gmm energy weight
beta: 0.001
# singularity weight
gamma: 0.005
# batch size
bs: 1024
# training device
d: cuda:0
dataset: asas_sn
# dropout
do: 0.5
# epochs
e: 2000
fold: false
# learning rate
lr: 0.0002
# estimation network size
ne: 16
# recurrent network size
nh: 96
# latent space size
nl: 8
# number of recurrent layers
nlayers: 2
# output size
nout: 1
# outlier family (ztf)
outlier_fam: periodic
# early stopping patience
patience: 1000
# number of repetitions
rep: 5
# weight decay weight
wd: 0.0
